name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.2,name=iPhone X', 'platform=tvOS Simulator,OS=13.2,name=Apple TV 4K']
    steps:
      - name: Build and test
        run: |
          xcodebuild -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker iOS" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO build test
          xcodebuild -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker OS X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO build test
          bash <(curl -s https://codecov.io/bash)
        env:
          destination: ${{ matrix.destination }}
