name: CI

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: xcodebuild test -scheme ByteBackpacker # swift test --enable-code-coverage is not yet supported
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
          file: bash $(swift test --show-codecov-path)
          fail_ci_if_error: True 
