name: CI

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: swift test --enable-code-coverage 
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: swift test --show-codecov-path
          name: codecov-umbrella 
